FROM python:3.11-slim

WORKDIR /app

COPY consumer/requirement.txt .
RUN pip3 install --no-cache-dir -r requirement.txt

COPY consumer/consumer_postgres.py .
COPY config.py .

ENV KAFKA_BROKER=kafka:9092 \
    TOPIC_CLASSIFIED=movie-comments-classified\
    POSTGRES_HOST=postgres \
    POSTGRES_PORT=5432 \
    POSTGRES_DB=sentiment_db \
    POSTGRES_USER=admin \
    POSTGRES_PASSWORD=password


CMD ["python", "-u", "consumer_postgres.py"]